name: 定期检查DedeCMS更新

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜 (UTC时间) 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
    - name: 设置Python环境
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 检出代码
      uses: actions/checkout@v2
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub beautifulsoup4
    - name: 运行更新脚本
      run: |
        python scripts/update_dedecms.py
